---
AllCops:
  TargetRubyVersion: 2.3

Style/ClassAndModuleChildren:
  Description: 'Most modules will use the non-nested syntax'
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/ClassLength:
  Description: 'Most modules and payloads are quite large. This is ok.'
  Enabled: true
  Exclude:
    - 'modules/**/*'
    - 'payloads/**/*'

Style/Documentation:
  Enabled: true
  Description: 'Most modules do not have class documentation.'
  Exclude:
    - 'modules/**/*'

Metrics/LineLength:
  Description: 'Modules often pattern match against very long strings when identifying targets.'
  Enabled: true
  Max: 180

Metrics/MethodLength:
  Enabled: true
  Description: 'While the style guide suggests 10 lines, exploit definitions often exceed 200 lines.'
  Max: 300

Style/WordArray:
  Enabled: false
  Description: 'Prefer consistent use of []'

Style/RedundantBegin:
  Exclude:
    - 'modules/**/*'

Documentation:
  Exclude:
    - 'modules/**/*'

Layout/IndentArray:
  Enabled: false
  Description: 'A lot of modules use a sensible indentation level that Rubocop does not like.'

Lint/UnusedMethodArgument:
  Description: 'A number of classes will contain unused parameters for documentation purposes.'
  Exclude:
    - 'lib/wpxf/**/*'

Style/ClassVars:
  Enabled: false
  Description: 'There are genuine use cases for using class vars.'

Metrics/BlockLength:
  Exclude:
   - spec/**/*